<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13713" started-at="2014-09-13T09:26:04Z" finished-at="2014-09-13T09:26:17Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13713" started-at="2014-09-13T09:26:04Z" finished-at="2014-09-13T09:26:17Z">
      <class name="com.example.tests.NewContact">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.example.tests.NewContact@36aa544]" name="setUp" is-config="true" duration-ms="7060" started-at="2014-09-13T13:26:04Z" finished-at="2014-09-13T13:26:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testNewUserCreation(com.example.tests.ContactData)[pri:0, instance:com.example.tests.NewContact@36aa544]" name="testNewUserCreation" duration-ms="6427" started-at="2014-09-13T13:26:11Z" data-provider="randomValidContactGenerator" finished-at="2014-09-13T13:26:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ContactData [contactName=Umma-980504295, secondName=Mila-774125910]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.example.tests.NewContact.testNewUserCreation(NewContact.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNewUserCreation -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.example.tests.NewContact@36aa544]" name="tearDown" is-config="true" duration-ms="207" started-at="2014-09-13T13:26:17Z" finished-at="2014-09-13T13:26:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.example.tests.NewContact -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
